source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "minimal-mistakes-jekyll", "~> 4.24.0"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-include-cache", "~> 0.2"
gem "webrick", "~> 1.7"
gem "csv"
gem "base64"
